Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        echo "10.0.0.10  master-node" >> /etc/hosts
        echo "10.0.0.11  worker-node01" >> /etc/hosts
        echo "10.0.0.12  worker-node02" >> /etc/hosts
    SHELL
    
    config.vm.define "master" do |master|
      master.vm.box = "bento/ubuntu-18.04"
      master.vm.hostname = "master-node"
      master.vm.network "private_network", ip: "10.0.0.10"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 4048
          vb.cpus = 2
      end
      master.vm.provision "shell", path: "scripts/common.sh"
      master.vm.provision "shell", path: "scripts/master.sh"
    end

    (1..2).each do |i|
  
    config.vm.define "node0#{i}" do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.hostname = "worker-node0#{i}"
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 1
      end
      node.vm.provision "shell", path: "scripts/common.sh"
      node.vm.provision "shell", path: "scripts/node.sh"
    end
    
    end
  end
#filename=Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant.configure("2") do |cf|
  # NFS Server
#  cf.vm.define "nfs-server" do |nfs|
#    nfs.vm.box = "archlinux/archlinux"
#    nfs.vm.hostname = "nfs-server.example.com"
#    nfs.vm.network "private_network", ip: "10.0.0.13"
#    nfs.vm.provider "virtualbox" do |n|
#      n.name = "nfs-server"
#      n.memory = 1024
#      n.cpus = 1
#    end
#    nfs.vm.provision "shell",path: "bootstrap_nfs.sh"
#  end

